foo = ['a', 'b', 'c']
print(foo[3])      # will this result in an error?

# Yes, this will print an error because index is only up to [2]